src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from accounts.views import InternalServerErrorView, PageNotFoundView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('500/', view=InternalServerErrorView.as_view(), name='internal-server-error'),
    path('404/', view=PageNotFoundView.as_view(), name='page-not-found'),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('orders/', include('orders.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from . import views as main_views

urlpatterns = [
    path('', view=main_views.IndexView.as_view(), name='home'),
    path('movies/', view=main_views.MovieListView.as_view(), name="movies"),
    path('movies/<slug:slug>/', view=main_views.MovieDetailView.as_view(), name='movie-details'),
    path('movies/<slug:slug>/addToWishlist/', view=main_views.AddRemoveWhislistView.as_view(), name="add-to-wishlist"),

    # API Views
    path('api/v1/movies/', view=main_views.MovieListApiView.as_view(), name='movie-list'),
    path('api/v1/<slug:slug>/like-dislike/', view=main_views.MovieLikeAndDislikeView.as_view(), name="movie-like-dislike"),
    path('api/v1/<slug:slug>/addComment/', view=main_views.AddCommentToMovieView.as_view(), name="add-comment-to-movie"),
    path('api/v1/wishlist/', view=main_views.WishlistListView.as_view(), name="wishlist"),
]

src/main/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from datetime import datetime

import uuid

User = get_user_model()

class Cast(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female')
    ]
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f'#{self.name}'
    
    def clean(self) -> None:
        self.title = self.title.lower()
        return super().clean()
    
    def save(self, *args, **kwargs):
        self.full_clean()
        super.save(*args, **kwargs)

class Movie(models.Model):

    GENRE_CHOICES = [
            ('ACTION', 'Action'),
            ('COMEDY', 'Comedy'),
            ('DRAMA', 'Drama'),
            ('HORROR', 'Horror'),
            ('ROMANCE', 'Romance'),
            ('SCIENCE_FICTION', 'Science Fiction'),
            ('FANTASY', 'Fantasy'),
        ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='movies')

    uuid = models.UUIDField(default=uuid.uuid4)

    title = models.CharField(max_length=150, unique=True, db_index=True)
    description = models.TextField(null=True, blank=True)
    release_date = models.DateField(null=True)

    genre = models.CharField(max_length=100, choices=GENRE_CHOICES, db_index=True)
    length = models.PositiveIntegerField(default=1)
    
    image_card = models.ImageField(upload_to='movie/images/')
    image_cover = models.ImageField(upload_to='movie/covers/')
    video = models.FileField(upload_to='movie_videos/')

    director = models.CharField(max_length=100, null=True, db_index=True)

    is_paid = models.BooleanField(default=False)

    views = models.IntegerField(default=0)
    ratings = models.FloatField(default=1.0, validators=[MaxValueValidator(10.0), MinValueValidator(1.0)], db_index=True)

    tags = models.ManyToManyField(Tag, through="MovieTag")
    casts = models.ManyToManyField(Cast, through="MovieCast")

    like_counts = models.PositiveIntegerField(default=0)

    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.title
    
    def is_high_rated(self):
        now = timezone.now()
        return self.ratings >= 8.5 and self.release_date <= now
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=30) <= self.release_date <= now
    
    def is_most_viewed(self):
        now = timezone.now()
        return self.views >= 10000 and self.release_date <= now

    def get_absolute_url(self):
        return reverse("movie-details", kwargs={"slug": self.slug})
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class MovieCast(models.Model):
    cast = models.ForeignKey(Cast, on_delete=models.CASCADE, related_name="movies")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="movie_casts")

    def __str__(self) -> str:
        return f'{self.cast.name}-{self.movie.title}'

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["cast_id", "movie_id"],
                name = "unique_movie_cast"
            )
        ]
    
class MovieTag(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name="movies")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="movie_tags")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["tag_id", "movie_id"], name="unique_movie_tag"
            )
        ]

    def __str__(self) -> str:
        return f'{self.tag__name}-{self.movie__title}'
    
class MovieWishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="wishlist")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='wishlist_users')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user_id", "movie_id"], name="unique_movie_user"
            )
        ]

    def __str__(self) -> str:
        return f'{self.user.username}-{self.movie.title}'
    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='comments')
    value = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.user.username}_{self.movie.title}'
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='likes')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user_id", "movie_id"],
                name = "unique_like_movie_user"
            )
        ]

    def __str__(self) -> str:
        return f'{self.user.username}_{self.movie.title}'
    

src/main/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['value']

src/main/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView
from django.views import View
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from django.conf import settings
from django.core.serializers import serialize
from django.contrib import messages
from django.db import transaction
from django.db.models import Q, Prefetch

from .models import Movie, MovieWishList, Like, Comment
from .forms import CommentForm

import json
import re

# Create your views here.
class IndexView(TemplateView):
    template_name = 'main/index.html'

class AddRemoveWhislistView(View):

    def post(self, request, *args, **kwargs):
        user = request.user

        if not user.is_authenticated:
            return JsonResponse({
                "error":True,
                "message":"User is not authenticated!",
                "data":{}
            }, status=400)
        
        movie = Movie.objects.filter(slug=kwargs['slug']).first()

        if not movie:
            return JsonResponse({
                "error":True,
                "message":"Invalid Slug field!",
                "data":{}
            }, status=404)
        
        obj, created = MovieWishList.objects.get_or_create(user=user, movie=movie)

        if not created:
            obj.delete()
            return JsonResponse({
                "error":False,
                "message":"Added to your wishlist!",
                "data":{
                    'in_wishlist':created
                }
            })

        return JsonResponse({
            "error":False,
            "message":"Added to your wishlist!",
            "data":{
                'in_wishlist':created
            }
        })


class MovieDetailView(LoginRequiredMixin, DetailView):
    template_name = 'main/movie_detail.html'
    queryset = Movie.objects.all()
    context_object_name = "movie"

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object()

        with transaction.atomic():
            self.object.views += 1
            self.object.save()

        context = self.get_context_data(object=self.object)

        instance = MovieWishList.objects.filter(user=request.user, movie=self.object)
        
       # Check if the requested user has liked the movie
        user = self.request.user
        context['has_liked'] = Like.objects.filter(user=user, movie=self.object).exists()

        # Check if the requested user has added the movie to their wishlist
        context['in_wishlist'] = MovieWishList.objects.filter(user=user, movie=self.object).exists()

        # Add comments context
        context['comments'] = self.object.comments.all().order_by('-created_at')[:10]

        return self.render_to_response(context)
    
    def get_object(self, queryset = None):
        movie = self.queryset.filter(slug=self.kwargs["slug"]).prefetch_related(Prefetch("comments", queryset=Comment.objects.order_by("-created_at").select_related("user"))).first()
        if movie is None:
            raise Http404("Not Found")
        return movie


class MovieListView(LoginRequiredMixin, ListView):
    queryset = Movie.objects.all()
    paginate_by = 3
    context_object_name = "movies"
    template_name = "main/movie_list.html"

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        ordering = self.request.GET.get('ordering', '-ratings')
        genre = self.request.GET.get('genre', '')

        filter_condition = Q()
        if q: 
            filter_condition |= Q(title__icontains=q)
            filter_condition |= Q(director__iexact=q)
            queryset = queryset.filter(filter_condition)

        if genre:
            queryset = queryset.filter(genre__iexact=genre)

        queryset = queryset.order_by(ordering)
        return queryset
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        query_params = re.sub(r'page=\d&', '', self.request.GET.urlencode()) # Capture current query parameters
        query_params = re.sub(r'page=\d', '', query_params)
        context['query_params'] = query_params
        return context

class MovieListApiView(View):
    querset = Movie.objects.all()

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serialized = serialize('json', queryset=queryset[:10])

        return JsonResponse({
            "error":False,
            "movies": json.loads(serialized)
        }, status=200)
    
    def get_queryset(self):
        queryset = self.querset
        q = self.request.GET.get('q')

        filter_condition = Q()
        if q: 
            filter_condition |= Q(title__icontains=q)
            filter_condition |= Q(director__iexact=q)
            filter_condition |= Q(genre__iexact=q)
            queryset = queryset.filter(filter_condition)
        else:
            queryset = Movie.objects.none()
        return queryset
    

class MovieLikeAndDislikeView(LoginRequiredMixin, View):
    
    def post(self, request, slug, *args, **kwargs):
        movie = Movie.objects.filter(slug=slug).first()

        if not movie:
            return JsonResponse({
                "error":True,
                "message":"Invalid slug field!",
                "data":{},
            }, status=404)
        
        instance, created = Like.objects.get_or_create(user=request.user, movie=movie)

        if created:
            with transaction.atomic():
                movie.like_counts += 1
                movie.save()

            return JsonResponse({
                "error":False,
                "message":"Movie liked!",
                "data":{
                    'has_liked':True,
                    'like_counts':movie.like_counts
                }
            })
        
        instance.delete()
        with transaction.atomic():
            movie.like_counts -= 1
            movie.save()

        return JsonResponse({
                "error":False,
                "message":"Movie disliked!",
                "data":{
                    'has_liked':False,
                    'like_counts':movie.like_counts
                }
            })


class AddCommentToMovieView(LoginRequiredMixin, View):
    form_class = CommentForm
    
    def post(self, request, *args, **kwargs):


        slug = kwargs['slug']

        movie = Movie.objects.filter(slug=slug).first()

        if not movie:
            return JsonResponse({
                "error":True,
                "movie":"Invalid slug field",
                "data":{},
            }, status=404)
        
        user = request.user
        form = self.form_class({'value':request.POST.get('comment')})


        if form.is_valid() is False:
            return JsonResponse({
                "error":True,
                "message":form.errors.pop('value')[0],
                "data":{}
            }, status=400)
        
        comment = Comment.objects.create(user=user, movie=movie, value=form.cleaned_data['value'])

        return JsonResponse({
            "error":False,
            "mesage":"Successfully added!",
            "data":{
                'user':user.username,
                'comment':json.loads(serialize('json', [comment]))[0],
            }
        }, status=201)
    

class WishlistListView(ListView):
    paginate_by = 3
    context_object_name = 'movies'

    def get(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return JsonResponse({
                "error":True,
                "message": "User is not authenticated.",
                "data": {}
            })
            
        response = super().get(request, *args, **kwargs)
        movies_serialized = serialize('json', response.context_data['movies'])
        page_obj = response.context_data["page_obj"]

        # previous
        if page_obj.has_previous(): previous = page_obj.previous_page_number()
        else: previous = ""

        # next
        if page_obj.has_next(): next = page_obj.next_page_number()
        else: next = ""

        return JsonResponse({
            "error":False,
            "message": "",
            "data": {
                "count": page_obj.paginator.count,
                "previous": previous,
                "next": next,
                "results": json.loads(movies_serialized)
            }
        })

    def get_queryset(self) -> QuerySet[Any]:
        user = self.request.user
        return Movie.objects.filter(wishlist_users__user=user)
    

src/templates/main/movie_detail.html
{% extends "common/base.html" %}
{% load static %}
{% load myfilters %}

{% block css %}

<style>
  *{
    margin:0;
    padding:0;
    box-sizing:border-box;
  }
      .video-container{
        display: grid;
        place-items: center;
        padding: 25px;
    }

    .master-container{
        height: 100vh;
        width: 100%;
    }

    .video{
        max-height: 100vh;
        max-width: 1080px;
        height: 80vh;
        box-shadow: rgba(255, 0, 0, 1) 0px 5px 15px;
    }

    .error__nav {
      margin: 40px auto 0;
      text-align: center;
      width: 100%;
      height: 50%;
      max-width: 1080px;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: rgba(255, 0, 0, 1) 0px 5px 15px;
      }

      .e-nav__link {
          height: 45px;
          line-height: 45px;
          width: 170px;
          display: inline-block;
          vertical-align: top;
          margin: 0 15px;
          border: 1px solid #181828;
          color: #181828;
          text-decoration: none;
          font-family: 'Montserrat', sans-serif;
          text-transform: uppercase;
          font-size: 11px;
          letter-spacing: .1rem;
          background-color: #e50914;
          position: relative;
          overflow: hidden;
          }
  
          .e-nav__link:before {
          content: '';
          height: 200px;
          background: #212121;
          position: absolute;
          top: 70px;
          right: 70px;
          width: 260px;
          -webkit-transition: all .3s;
          transition: all .3s;
          -webkit-transform: rotate(50deg);
                  transform: rotate(50deg);
          }
  
          .e-nav__link:after {
          -webkit-transition: all .3s;
          transition: all .3s;
          z-index: 999;
          position: relative;
          }
  
          .e-nav__link:after {
          content: "Subscribe to Watch";
          }
  
          .e-nav__link:hover:before {
          top: -60px;
          right: -50px;
          }
  
          .e-nav__link:hover {
          color: #fff;
          }
  
          .e-nav__link:nth-child(2):hover:after {
            color: #fff;
            }

          #comment-box{
            height: 150px;
            overflow-y: scroll;
            background-color: #212121 !important;
          }

          .list-group-item{
            background-color: black;
            color: white;
            margin-top: 5px;
          }

          /* Hide scrollbar for Chrome, Safari and Opera */
          #comment-box::-webkit-scrollbar {
              display: none;
          }

          /* Hide scrollbar for IE, Edge and Firefox */
          #comment-box {
            -ms-overflow-style: none;  /* IE and Edge */
            scrollbar-width: none;  /* Firefox */
          }
</style>

{% endblock css %}

{% block body %}

{% include "includes/nav.html" %}

<div class="container">

  <h1>{{movie.title}}</h1>

  <div class="row bg-dark p-3">
    <div class="col-3">
      <div style="height: 300px; width:100%;">
        <img src="{{movie.image_card.url}}" alt="{{movie.title}}" style="height:100%; width:100%; object-fit:cover">
      </div>
    </div>

    <div class="col-9" style="position:relative">
      <form method="POST" action="{% url 'add-to-wishlist' movie.slug %}" id="wishlist-form" style="position: absolute; right: 10px;">{% csrf_token %}
        {% if not in_wishlist %}
        <button class="btn btn-outline-danger" type="submit" style="padding: 4px 10px;">Add to wishlist <i class="fa fa-plus"></i></button>
        {% else %}
        <button class="btn btn-outline-danger" type="submit" style="padding: 4px 10px;">Remove from wishlist <i class="fa-solid fa-xmark"></i></i></button>
        {% endif %}
      </form>

      <p><small class="muted">Directed By: </small>{{movie.director}}</p>
      <p><small class="muted">Release Date: </small>{{movie.release_date}}</p>
      <p><small class="muted">Genre: </small>{{movie.get_genre_display}}</p>
      <p><small class="muted">Views: </small>{{movie.views}}</p>
      <p><small class="muted">Ratings: </small>{{movie.ratings}}</p>
      <details style="margin: 15px 0;">
        <summary>Description</summary>
        <p>{{movie.description}}</p>
      </details>
    </div>
  </div>
</div>


<div class="container movie-info-container">
  <div class="row master-container p-3">
    <div class="col-12 video-container">
        {% if not movie.is_paid or user.is_premium_user %}
        <video class="video" id="video1" controls>
            <source src="{{movie.video.url}}" type="video/mp4">
            Your browser does not support HTML video.
        </video>
        {% else  %}
        <div class="error__nav e-nav">
          <a href="{% url 'subscriptions' %}" class="e-nav__link"></a>
        </div>
        {% endif %}
    </div>
  </div>

  <div class="container" style="width: 80%;">

    <div class="d-flex flex-row align-items-center" style="margin: 1rem 0.375rem;">
      
      <form id="likeDislikeForm"> {% csrf_token %}
          <div id="likeDislikeButton" style="place-content: center;">
              {% if has_liked == True %}
              <button type="submit" class="btn btn-danger m-0"><i class="fa-solid fa-heart"></i></button>
              {% else %}
              <button type="submit" class="btn btn-outline-danger m-0"><i class="fa-regular fa-heart"></i></button>
              {% endif %}
          </div>
      </form>

      <p id="likeCount" style="margin:0 5px;">{{movie.like_counts}} Likes</p>
    </div>

    <p class="my-2" style="font-size: 20px;">Comments:</p>

    <div id="comment-box" class="mb-2">
      

      
      <ul class="list-group list-group-flush mx-2 rounded" id="comment-list">
        {% for comment in comments %}
        <li class="list-group-item my-1"> <strong>{{comment.user.username}}:</strong> {{comment.value}}</li>
        {% endfor %}
      </ul>

      {% if not comments %}
      <h4 class="mt-3" style="text-align: center;" id="no-comment">No comments Yet!.</h4>
      {% endif %}
    </div>

    <form class="input-group mb-3" id="post-comment-form">
      <input type="text" class="form-control" name="comment" placeholder="Your Comment..." aria-describedby="basic-addon2" required>
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" style="margin: 0 !important;" type="submit">Add Comment</button>
      </div>
    </form>
  </div>
</div>

{% include "includes/trending.html" %}

{% include "includes/top_rated_movies.html" %}

{% include "includes/recently_published.html" %}

{% include "includes/footer.html" %}

{% endblock body %}


{% block js %}

<script>

  document.getElementById('wishlist-form').addEventListener('submit', async (e) => {
    e.preventDefault();

    let URL = "{% url 'add-to-wishlist' movie.slug %}"
    let form = e.target;

    try{
        let response = await fetch(URL, {
        method:'POST',
        headers:{
          'X-CSRFToken':"{{csrf_token}}"
        },
      })

      if (!response.ok){
        throw new Error('Server responsed with an error!');
      }

      let response_data = await response.json();

      if (!response_data.data['in_wishlist']){
        form.innerHTML = `<button class="btn btn-outline-danger" type="submit" style="padding: 4px 10px;">Add to wishlist <i class="fa fa-plus"></i></button>`
      }
      else{
        form.innerHTML = `<button class="btn btn-outline-danger" type="submit" style="padding: 4px 10px;">Remove from wishlist <i class="fa-solid fa-xmark"></i></i></button>`
      }
    }
    catch (error){
      alert(error);
    }
    
  });

  document.getElementById('post-comment-form').addEventListener('submit', async (e) => {
      e.preventDefault();

      let URL = "{% url 'add-comment-to-movie' movie.slug %}";
      let form = e.target;
      let formData = new FormData(form);
      let commentList = document.getElementById('comment-list');
      let noComment = document.getElementById('no-comment');

      try{
        let response = await fetch(URL, {
          method:'POST',
          body:formData,
          headers:{
            'X-CSRFToken':'{{csrf_token}}'
          }
        });

        if (!response.ok){
          throw new Error("Network responsed with an error.")
        }
        

        let response_data = await response.json();

        let data = response_data.data;
        let user = data.user;

        let comment = data.comment.fields.value;
        let liHTML = `<li class="list-group-item"> <strong>${user}:</strong> ${comment}</li>`;         
        let li = document.createElement('li');
        li.innerHTML = liHTML;
        if (noComment) noComment.style.display = 'none';
        commentList.insertBefore(li, commentList.children[0]);

      }
      catch (error){
        alert(error);
      }
  });

  document.getElementById('likeDislikeForm').addEventListener('submit', async (e) => {

    e.preventDefault();

    const alertBox = document.getElementById('alert-box');
    const message = document.getElementById('message'); 
    let URL = "{% url 'movie-like-dislike' movie.slug %}";

    let form = e.target;
    let p = document.getElementById('likeCount');

    try {
      let response = await fetch(URL, {
        method: 'POST',
        headers: {
        'X-CSRFToken': '{{ csrf_token }}'
          }
        });
        
        if (!response.ok) {
          throw new Error('An unknown error occured. Network responded with an error.');
        }
        
        let response_data = await response.json();

        let has_liked = response_data.data.has_liked;
        let like_counts = response_data.data.like_counts;

        if (has_liked==true){
          form.innerHTML = '<button type="submit" class="btn btn-danger m-0"><i class="fa-solid fa-heart"></i></button>'
        }
        else{
          form.innerHTML = '<button type="submit" class="btn btn-outline-danger m-0"><i class="fa-regular fa-heart"></i></button>'
        }

        p.innerText = `${like_counts} Likes`;

        } catch (error) {
          alert(error);
        }
    });
</script>

{% endblock js %}